services:
  reactapp:
    build:
      context: ./
      dockerfile: app/Dockerfile
    network_mode: host
    volumes:
      - ./app/src:/app/src

  nodeserver:
    restart: always
    build:
      context: ./
      dockerfile: server/Dockerfile
    network_mode: host
    volumes:
      - ./server/src:/server/src
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5433
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - ./database/init/:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  ignore:
  pgdata:

          